#!/bin/bash

INTERFACE="wlan1"

CHANNELS_2_4GHZ=(1 2 3 4 5 6 7 8 9 10 11)
CHANNELS_5GHZ=(36 40 44 48 52 56 60 64 100 104 108 112 116 120 124 128 132 136 140 144 149 153 157 161 165)

CHANNELS=("${CHANNELS_2_4GHZ[@]}" "${CHANNELS_5GHZ[@]}")


DURATION=10

if ! iwconfig $INTERFACE > /dev/null 2>&1; then
    echo "Interface $INTERFACE not found or not up."
    exit 1
fi

echo "Starting channel hopping on $INTERFACE."

while true; do
    for CHANNEL in "${CHANNELS[@]}"; do
        echo "Switching to channel $CHANNEL"
        iwconfig $INTERFACE channel $CHANNEL
        sleep $DURATION
    done
done

